version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/node:16 # Base image for Node.js
    working_directory: ~/repo

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout # Check out the code from your repository
      - setup_remote_docker: # Enables Docker in Docker without versioning
          docker_layer_caching: true # Optional, speeds up builds
      - run:
          name: Build Docker image
          command: |
            IMAGE_TAG=${CIRCLE_SHA1:0:7} # Get the first 7 characters of the commit SHA
            docker build -t reneboy/docility:${IMAGE_TAG} .
      - run:
          name: Log in to Docker Hub
          command: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - run:
          name: Push Docker image
          command: docker push reneboy/docility:${IMAGE_TAG}

workflows:
  version: 2
  build_and_push:
    jobs:
      - build
