version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/python:3.8  # Use an appropriate base image for your build

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true  # Enable layer caching for faster builds

      - run:
          name: Build Docker Image
          command: |
            IMAGE_TAG=${CIRCLE_SHA1:0:7} # Get the first 7 characters of the commit SHA
            docker build -t reneboy/docility:${IMAGE_TAG} .

      - run:
          name: Push Docker Image
          command: |
            IMAGE_TAG=${CIRCLE_SHA1:0:7}
            echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
            docker push reneboy/docility:${IMAGE_TAG}

workflows:
  version: 2
  build_and_push:
    jobs:
      - build
