version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/node:14 # Use the Node.js image as base
    working_directory: ~/repo

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build the Vue App
          command: npm run build
      - run:
          name: Login to Docker Hub
          command: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - run:
          name: Build Docker Image
          command: |
            # Use the commit SHA as part of the tag for incremental versioning
            IMAGE_TAG=${CIRCLE_SHA1:0:7} # Get the first 7 characters of the commit SHA
            docker build -t reneboy/docility:${IMAGE_TAG} .
      - run:
          name: Push Docker Image to Docker Hub
          command: |
            IMAGE_TAG=${CIRCLE_SHA1:0:7} # Get the first 7 characters of the commit SHA
            docker push reneboy/docility:${IMAGE_TAG}

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
                - feature/*
